<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>


    <xacro:property name="chassis_radius" value="0.20"/>
    <xacro:property name="chassis_length" value="0.112"/>
    <xacro:property name="chassis_height" value="0.072"/>
    <xacro:property name="chassis_mass" value="2.0"/>
    <xacro:property name="tripod_radius" value="0.0115"/>
    <xacro:property name="tripod_length" value="0.441"/>
    <xacro:property name="tripod_mass" value="1.0"/>
    <xacro:property name="holder_length" value="0.17"/>
    <xacro:property name="holder_width" value="0.17"/>
    <xacro:property name="holder_height" value="0.003"/>
    <xacro:property name="holder_mass" value="0.1"/>
    <xacro:property name="wheel_radius" value="0.03185"/>
    <xacro:property name="wheel_thickness" value="0.0255"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.0"/>
    <xacro:property name="wheel_offset_y" value="0.164"/>
    <xacro:property name="wheel_offset_z" value="${-chassis_height-chassis_length/2+wheel_radius}"/>
    <xacro:property name="caster_wheel_radius" value="0.02"/>
    <xacro:property name="caster_wheel_mass" value="0.04"/>
    <xacro:property name="caster_wheel_offset_x" value="0.1515"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 ${chassis_height+chassis_length/2}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz = "0 0 0"/>
            <geometry>
                <cylinder length="${chassis_length}" radius="${chassis_radius}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz = "0 0 ${chassis_length/2}"/>
            <geometry>
                <cylinder length="${chassis_length}" radius="${chassis_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${chassis_mass}" length="${chassis_length}" radius="${chassis_radius}">
            <origin xyz="0 0 ${chassis_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- TRIPOD -->

    <joint name="tripod_joint" type="fixed">
        <parent link="chassis"/>
        <child link="tripod"/>
        <origin xyz="0 0 ${chassis_height/2}"/>
    </joint>

    <link name="tripod">
        <visual>
            <origin xyz = "0 0 ${tripod_length/2}"/>
            <geometry>
                <cylinder length="${tripod_length}" radius="${tripod_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz = "0 0 ${tripod_length/2}"/>
            <geometry>
                <cylinder length="${tripod_length}" radius="${tripod_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${tripod_mass}" length="${tripod_length}" radius="${tripod_radius}">
            <origin xyz="0 0 ${tripod_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="tripod">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- HOLDER -->

    <joint name="holder_joint" type="fixed">
        <parent link="tripod"/>
        <child link="holder"/>
        <origin xyz="0 0 ${tripod_length}"/>
    </joint>

    <link name="holder">
        <visual>
            <origin xyz = "0 0 ${holder_height/2}"/>
            <geometry>
                <box size="${holder_length} ${holder_width} ${holder_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz = "0 0 ${holder_length/2}"/>
            <geometry>
                <box size="${holder_length} ${holder_width} ${holder_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${holder_mass}" x="${holder_length}" y="${holder_width}" z="${holder_height}">
            <origin xyz="${holder_length/2} 0 ${holder_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="holder">
        <material>Gazebo/Blue</material>
    </gazebo>

    

    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="chassis"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} ${wheel_offset_z}" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>




    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="chassis"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} ${wheel_offset_z}" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>


    <!-- FRONT CASTER WHEEL LINK -->

    <joint name="front_caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="front_caster_wheel"/>
        <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
    </joint>


    <link name="front_caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="front_caster_wheel">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>
    

    <!-- REAR CASTER WHEEL LINK -->

    <joint name="rear_caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="rear_caster_wheel"/>
        <origin xyz="${-caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
    </joint>


    <link name="rear_caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="rear_caster_wheel">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

</robot>
